import 'package:cloud_firestore/cloud_firestore.dart';

import '../models/listing.dart';
import 'logger_service.dart';

/// FirestoreService handles all database operations for listings.
/// 
/// This service layer abstracts Firestore operations, ensuring clean separation
/// between UI and backend logic. All CRUD operations go through this service,
/// which is then exposed to the UI via ListingProvider.
/// 
/// Database Structure:
/// ```
/// /listings
///   ├─ id (auto-generated)
///   ├─ name (string)
///   ├─ category (string: Hospital, Restaurant, etc.)
///   ├─ address (string)
///   ├─ contact (string)
///   ├─ description (string)
///   ├─ latitude (number)
///   ├─ longitude (number)
///   ├─ createdBy (string: user UID)
///   └─ timestamp (Timestamp)
/// ```
class FirestoreService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  CollectionReference<Map<String, dynamic>> get _listings =>
      _firestore.collection('listings');

  /// Retrieves all listings from Firestore as a real-time stream.
  /// 
  /// Returns listings ordered by most recent first (descending timestamp).
  /// The stream automatically updates whenever Firestore data changes,
  /// allowing UI to reflect updates in real-time through ListingProvider.
  /// 
  /// Returns: Stream<List<Listing>> - Real-time updates of all listings
  Stream<List<Listing>> getListings() {
    LoggerService.firestore('READ', 'listings');
    return _listings
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
          LoggerService.info('Fetched ${snapshot.docs.length} listings');
          return snapshot.docs
              .map((doc) => Listing.fromFirestore(doc))
              .toList();
        })
        .handleError((error) {
          LoggerService.firestore('READ ERROR', 'listings', '', error);
          throw error;
        });
  }

  /// Retrieves all listings created by a specific user as a real-time stream.
  /// 
  /// Note: Firestore requires a composite index for combined where() + orderBy()
  /// queries. As a workaround, we fetch all listings and filter/sort in-memory.
  /// This is acceptable for apps with <10k listings.
  /// 
  /// Parameters:
  ///   uid: The Firebase user ID to filter listings by
  /// 
  /// Returns: Stream<List<Listing>> - User's listings in reverse chronological order
  Stream<List<Listing>> getListingsByUser(String uid) {
    LoggerService.firestore('READ USER LISTINGS', 'listings', uid);
    // Note: Firestore requires a composite index for where() + orderBy()
    // We fetch all listings and filter/sort in-memory as a workaround
    return _listings
        .snapshots()
        .map((snapshot) {
          final listings = snapshot.docs
              .map((doc) => Listing.fromFirestore(doc))
              .toList();
          // Filter by user in-memory
          final userListings = listings
              .where((listing) => listing.createdBy == uid)
              .toList();
          // Sort by timestamp descending
          userListings.sort((a, b) => b.timestamp.compareTo(a.timestamp));
          LoggerService.info(
            'Fetched ${userListings.length} listings for user $uid',
          );
          return userListings;
        })
        .handleError((error) {
          LoggerService.error('Error reading user listings for $uid', error);
          throw error;
        });
  }

  /// Creates a new listing in Firestore.
  /// 
  /// The document ID is auto-generated by Firestore and returned for reference.
  /// This allows the caller to update the listing object with the new ID.
  /// 
  /// Parameters:
  ///   listing: The Listing object to create (without ID)
  /// 
  /// Returns: Future<String> - The newly created document ID
  /// 
  /// Throws: Exception if Firestore write fails
  Future<String> createListing(Listing listing) async {
    try {
      LoggerService.firestore('CREATE', 'listings', listing.name);
      final docRef = await _listings.add(listing.toMap());
      final docId = docRef.id;
      LoggerService.info(
        'Successfully created listing: ${listing.name} with ID: $docId',
      );
      return docId;
    } catch (e) {
      LoggerService.firestore('CREATE ERROR', 'listings', listing.name, e);
      rethrow;
    }
  }

  /// Updates an existing listing in Firestore.
  /// 
  /// Only updates the fields provided in listing.toMap().
  /// The listing must have a valid ID from a previous create or read operation.
  /// 
  /// Parameters:
  ///   listing: The Listing object with updated fields (must have valid ID)
  /// 
  /// Throws: Exception if listing ID is invalid or Firestore write fails
  Future<void> updateListing(Listing listing) async {
    try {
      LoggerService.firestore('UPDATE', 'listings/${listing.id}', listing.name);
      await _listings.doc(listing.id).update(listing.toMap());
      LoggerService.info('Successfully updated listing: ${listing.name}');
    } catch (e) {
      LoggerService.firestore(
        'UPDATE ERROR',
        'listings/${listing.id}',
        listing.name,
        e,
      );
      rethrow;
    }
  }

  /// Deletes a listing from Firestore.
  /// 
  /// Parameters:
  ///   id: The document ID of the listing to delete
  /// 
  /// Throws: Exception if listing ID is invalid or Firestore delete fails
  Future<void> deleteListing(String id) async {
    try {
      LoggerService.firestore('DELETE', 'listings/$id', '');
      await _listings.doc(id).delete();
      LoggerService.info('Successfully deleted listing: $id');
    } catch (e) {
      LoggerService.firestore('DELETE ERROR', 'listings/$id', '', e);
      rethrow;
    }
  }
}
